settings:
    legacy:
        force: false
        interval: 0s
schema:
    - name: supervisord
      path: .
      commands:
          run:
              status: true
      args:
          - --configuration="./test/supervisord.conf"
      watcher:
          extensions:
              - go
          paths:
              - /
          ignored_paths:
              - .git
              - .realize
              - vendor
